/**
 * This file was generated by dblet from the database schema.
 * Please do not edit it manually.
 */

import type { ColumnType } from "dblet/kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Users {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  name: string;
}

export interface DB {
  users: Users;
}

declare module "dblet" {
  interface Register {
    db: DB;
  }
}
