import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import type { Kysely } from "kysely";

const HEADER = `/**
 * This file was generated by dblet from the database schema.
 * Please do not edit it manually.
 */`;

const REGISTER = `declare module "dblet" {
  interface Register {
    db: DB;
  }
}`;

export function renderTypes(generated: string): string {
  // Apps may not depend on kysely directly, so import its types through dblet.
  const body = generated.trim().replaceAll('from "kysely"', 'from "dblet/kysely"');

  return `${HEADER}\n\n${body}\n\n${REGISTER}\n`;
}

// Returns whether the file was written.
export async function generateTypes(db: Kysely<any>, outFile: string): Promise<boolean> {
  // Imported lazily: kysely-codegen requires typescript, which production installs may lack.
  const { generate, PostgresDialect } = await import("kysely-codegen");

  const generated = await generate({
    db,
    dialect: new PostgresDialect(),
    outFile: null,
    skipAutogeneratedFileComment: true,
  });
  const content = renderTypes(generated);
  const current = await readFile(outFile, "utf8").catch(() => undefined);

  if (content === current) {
    return false;
  }

  await mkdir(dirname(outFile), { recursive: true });
  await writeFile(outFile, content);

  return true;
}
